# Type Labels (for automation and changelog)
- name: "type:feat"
  color: "0e8a16"
  description: "New feature or enhancement"

- name: "type:fix"
  color: "d73a4a"
  description: "Bug fix"

- name: "type:docs"
  color: "0075ca"
  description: "Documentation changes"

- name: "type:chore"
  color: "fef2c0"
  description: "Maintenance and chores"

# Area Labels (component filtering)
- name: "area:cli"
  color: "c2e0c6"
  description: "Leger CLI (cmd/leger)"

- name: "area:daemon"
  color: "c2e0c6"
  description: "Legerd daemon (cmd/legerd)"

- name: "area:docs"
  color: "c2e0c6"
  description: "Documentation"

# Special Labels (high-value human use)
- name: "breaking-change"
  color: "b60205"
  description: "Breaking API change (triggers major version)"

- name: "good-first-issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help-wanted"
  color: "008672"
  description: "Extra attention needed"
