name: Semantic PR

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: write
  statuses: write

jobs:
  validate:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            chore
          scopes: |
            cli
            daemon
            docs
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" didn't match the pattern.
            Please ensure the subject doesn't start with uppercase.
      
      - name: Add type label
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const typeMatch = title.match(/^(\w+)(?:\(([^\)]*)\))?:/);
            
            if (typeMatch) {
              const type = typeMatch[1];
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [`type:${type}`]
              });
            }
